name: Code quality check

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  quality-check:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: API's code quality check
        run: pnpm --filter ./api lint

      - name: API's type check
        run: pnpm --filter ./api type-check

      - name: API's code formatter
        run: pnpm --filter ./api prettier:writer

      - name: Client's code quality check
        run: pnpm --filter ./client lint

      - name: Client's type check
        run: pnpm --filter ./client type-check

      - name: Client's code formatter
        run: pnpm --filter ./client prettier:writer
